### ISSUE TITLE
Using the causal inference for company reviews

### ISSUE THREAD

**Issue by igormis** [rpryzant/causal_selection#1]
Hi, nice work and I think I could really use the causal inference for the following problem.
I have user reviews and score (from 1 to 5) for each company in a separate file: `companyX.tsv` in the following format:
`title   descr     score`

The title is the title of the review, where the descr is the full text that matches a rating that the user gave to that companyX (int number between 1 and 5).
Each company has a separate file and the number of rows of that file is the number of reviews given for that company.

However, I have problem in mapping my input to yours I a missing the control (Brand), what data ti use for this control parameter? Do you have any suggestions?

**Comment by rpryzant** [comment]
Yup, so in our framework you have to explicitly code the confounds. I'm not familiar enough with your space to recommend a sufficient proxy, sorry!
